config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'posts#index'
  resources :posts
  resources :users
  resources :answers
  resources :rooms

  patch '/answers/:id/unread', action: :unread, controller: 'answers'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :body, presence: true

  belongs_to :post
  belongs_to :user
  belongs_to :room

  def unread
    self.read = false
    self.save!
  end

  # Check if this answer is the first answer
  # ==== parameters
  # * +post_id+ - Post you answer
  # * +user_id+ - Your user id
  # * +room_id+ - This room's id
  def first_answer?(post_id: nil, user_id: nil, room_id: nil)
    # Return false if room_id already exists. This means this is not a new answer.
    return false if room_id
    # Return true if there is no Answer with the post_id and user_id passed as arguments.
    # This means this is a new answer.
    post = Post.find(post_id)
    !Answer.find_by(post_id: post_id, user_id: user_id)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @room = Room.find_or_create_by(id: params[:room_id]) do |room|
      room.post_id = params[:post_id]
      room.answerer_user_id = params[:answerer_user_id]
      room.host_user_id = params[:host_user_id]
    end
    @answer = @room.answers.new(user_id: current_user.id, post_id: @room.post_id)
  end

  def create
    @answer = Answer.new(answer_params)
    @answer.user_id = current_user.id
    @post = Post.find(params[:answer][:post_id])
    @message_to = @answer.user_id == @answer.room.host_user_id ? @answer.room.answerer.email : @answer.room.host.email

    if @answer.save
      NoticeMailer.with(
        {
          message_from: @answer.user.name,
          room: @answer.room,
          message_to: @message_to
        }
      ).new_message.deliver_later
      respond_to do |format|
        format.html { redirect_to room_url(@answer.room), notice: "Message was successfully sent." }
        format.json { render :show, status: :created, location: @answer.post }
      end
    else
      respond_to do |format|
        format.html { render :new, post_id: @post.id }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # def update
  #   @answer = Answer.find(params[:id])
  #   respond_to do |format|
  #     if @answer.update(answer_params)
  #       format.html { redirect_to answers_url, notice: "Post was successfully updated." }
  #       format.json { render :index }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @answer.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # def unread
  #   @answer = Answer.find(params[:id])
  #   respond_to do |format|
  #     if @answer.unread
  #       format.html { redirect_to answers_url }
  #     else
  #       format.html { render :show }
  #       format.json { render json: @answer.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  private

    def answer_params
      params.require(:answer).permit(:body, :read, :snoozed_at, :post_id, :user_id, :room_id)
    end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/index.html.erb
<h1>Message Box</h1>
<div class="answers">
  <% @rooms.each do |room| %>

    <div class="original-post">
      <h2>
        <%= "#{room.post.date.to_s(:date_for_title)} #{room.post.start_time.to_s(:time_for_title)} - #{room.post.end_time.to_s(:time_for_title)}" %>
      </h2>
      <p><%= room.post.describe.truncate(60) %></p>
    </div>

    <% room.answers.order(created_at: :desc).each do |answer| %>

      <% if answer.room_id == current_user.id || answer.post.user_id == current_user.id %>
        <div class="answer">
          <% if !answer.read %>
            <span style="font-size: 24px; color: tomato;"><i class="far fa-envelope"></i></span>
          <% else %>
            <span style="font-size: 24px; color: Dodgerblue;"><i class="far fa-envelope-open"></i></i></span>
          <% end %>
            <span class="answerer"><%= link_to "#{answer.user.name} ( #{answer.created_at.strftime("%A, %b %d %-H:%M %p")} )", answer_path(answer) %></span>
        </div>
      <% end %>

    <% end %>

  <% end %>
</div>

app/views/answers/new.html.erb
<div class="form">
  <%= form_with(model: @answer) do |form| %>
    <div class="form-controller form-date">
      <%= form.text_area :body, rows: 10, placeholder: "Message here" %>
    </div>

    <%= form.hidden_field :post_id, value: @answer.post.id %>
    <%= form.hidden_field :room_id, value: @answer.room_id %>
    <div class="form-controller">
      <%= form.submit "Send Answer", class: 'button button-submit' %>
    </div>
  <% end %>
</div>

app/views/answers/show.html.erb
<div class="answer">

  <div id="post_answered">
    <h2>Post</h2>
    <div class="post">
      <p>Date: <%= "#{@answer.post.date.to_s(:date_for_title)}" %></p>
      <p>Time: <%= "#{@answer.post.start_time.to_s(:time_for_title)} - #{@answer.post.end_time.to_s(:time_for_title)}" %></p>
      <p>Posted by: <%= "#{@answer.post.user.name}" %></p>
      <div class="post-body">
        <p><%= @answer.post.kind_of_climbing.camelize %></p>
        <p><%= @answer.post.describe.truncate(30) %></p>
      </div>
    </div>
  </div>

  <div>
    <%= "Answer_id: #{@answer.id}" %>
    <%= "room_id: #{@answer.room_id}" %>
  </div>

  <div class="conversation">
    <% @answers.each do |answer| %>
      <div class="message<%= answer.user_id == current_user.id ? " message-mine" : " message-other" %>">
        <div class="message-inner">
          <h3>
            <span class="answerer"><%= "answer_id: #{answer.id}, room_id: #{answer.room_id}, #{answer.user.name}[#{answer.user_id}] ( #{answer.created_at.to_s(:time_for_body)} )" %></span>
          </h3>
          <p><%= answer.body %></p>
        </div>
      </div>
    <% end %>
  </div>

  <div class="post-link">
    <%= link_to 'Answer', new_answer_path(post_id: @answer.post_id, room_id: @answer.room_id), class: "button button-submit" %>
    <%= form_with model: @answer, url: { controller: 'answers', action: 'unread' } do |f| %>
      <%= f.hidden_field :read, :value => false %>
      <%= f.submit "Make this message unread", class: "button button-unread" %>
    <% end %>
    <%= link_to 'Back', answers_path %>
  </div>
</div>