config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'posts#index'
  resources :posts
  resources :users
  resources :answers
  resources :rooms

  patch '/answers/:id/unread', action: :unread, controller: 'answers'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :post
  # belongs_to :user, optional: true
  belongs_to :host, class_name: "User", foreign_key: "host_user_id", optional: true
  belongs_to :answerer, class_name: "User", foreign_key: "answerer_user_id", optional: true

  has_many :answers
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @posts = Post.joins(:rooms).where(rooms: {host_user_id: current_user.id}).or(Post.joins(:rooms).where(rooms: {answerer_user_id: current_user.id})).distinct
    @has_rooms = Room.where(host_user_id: current_user.id).or(Room.where(answerer_user_id: current_user.id))
  end

  def show
    @room = Room.find(params[:id])

    # Make all unread messages read.
    @room.answers.each do |answer|
      # if answer.read == false && answer.user_id != current_user.id
      if answer.read == false
        answer.read = true
        answer.save
      end
    end
  end

  def create
    room = Room.new(room_params)
    if room.save
      respond_to do |format|
        format.html { redirect_to :show, notice: "Message was successfully sent." }
        format.json { render :show, status: :create, location: room }
      end
    else
      respond_to do |format|
        format.html { render :show }
        format.json { render json: room.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def room_params
      params.require(:room).permit(:host_user_id, :answerer_user_id, :post_id)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<% if @has_rooms %>
  <% @posts.each do |post| %>
    <p><%= post.describe %></p>

    <% post.rooms.each do |room| %>
      <% if room.host_user_id == current_user.id || room.answerer_user_id == current_user.id %>
        <% latest_answer = room.answers.where.not(user_id: current_user.id).last %>
        <% if latest_answer %>
          <div class="room">
            <div class="answer">
              <% if !latest_answer.read %>
                <span style="font-size: 24px; color: tomato;"><i class="far fa-envelope"></i></span>
              <% else %>
                <span style="font-size: 24px; color: Dodgerblue;"><i class="far fa-envelope-open"></i></i></span>
              <% end %>
                <span class="answerer"><%= link_to "#{latest_answer.user.name} ( #{latest_answer.created_at.strftime("%A, %b %d %-H:%M %p")} )", room_path(room) %></span>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>

<% else %>
  <p>You don't have any messages.</p>
<% end %>

app/views/rooms/show.html.erb
<h2>Message Box</h2>
<div class="answers">

    <div id="post_answered">
      <div class="post">
        <div class="post-body">
          <p>
            [ <%= @room.post.kind_of_climbing.camelize %> ]
            <%= "#{@room.post.date.to_s(:date_for_title)}" %>
            (<%= "#{@room.post.start_time.to_s(:time_for_title)} - #{@room.post.end_time.to_s(:time_for_title)} ), " %>
            <%= "#{@room.post.user.name}" %>
          </p>
          <p><%= @room.post.describe %></p>
        </div>
      </div>
    </div>

    <div class="conversation">
      <% @room.answers.each do |answer| %>
        <div class="message<%= answer.user_id == current_user.id ? " message-mine" : " message-other" %>">
          <div class="message-inner">
            <h3>
              <span class="answerer"><%= "#{answer.user.name} ( #{answer.created_at.to_s(:time_for_body)} )" %></span>
            </h3>
            <p><%= answer.body %></p>
          </div>
        </div>
      <% end %>
    </div>

    <div class="post-link">
      <%= link_to 'Answer', new_answer_path(post_id: @room.post_id, room_id: @room.id), class: "button button-submit" %>
      <%= link_to 'Back', rooms_path %>
    </div>

</div>