config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'posts#index'
  resources :posts
  resources :users
  resources :answers
  resources :rooms

  patch '/answers/:id/unread', action: :unread, controller: 'answers'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  validates :date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  belongs_to :user
  
  has_many :rooms
  has_many :answers

  enum kind_of_climbing: {
    trad: 0,
    sport: 1,
    bouldering: 2,
    multi_pitches: 3
  }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts or /posts.json
  def index
    @posts = Post.where.not(user_id: current_user.id).order(date: :desc, start_time: :asc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        # format.html { redirect_to @post, notice: "Post was successfully created." }
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:date, :start_time, :end_time, :kind_of_climbing, :describe)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="form">
  <%= form_with(model: post) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-controller form-date">
      <%= form.label :date %>
      <%= form.date_select :date %>
    </div>

    <div class="form-controller">
      <div class="form-time">
        <%= form.label :start_time, 'Duration (Start to End)' %>
        <%= form.time_select :start_time %>
      </div>

      <span class="time_to_time">-</span>

      <div class="form-time">
        <%= form.time_select :end_time %>
      </div>
    </div>

    <div class="form-controller form-select-box">
      <%= form.label :kind_of_climbing %>
      <%= form.select :kind_of_climbing, Post.kind_of_climbings.keys, {prompt: "Select"}, class: "select-box" %>
    </div>

    <div class="form-controller">
      <%= form.label :description %>
      <%= form.text_area :describe, rows: 10 %>
    </div>

    <div class="form-controller">
      <%= form.submit "Create Post", class: 'button button-submit' %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

  <% @posts.each do |post| %>
    <div class="post">
      <h2>
        <span class="post-owner"><%= link_to post.user.name, post_path(post) %></span>
        <span class="date"><%= "#{post.date.to_s(:date_for_title)}" %></span>
        <br>
        <span class="time"><%= "#{post.start_time.to_s(:time_for_title)} - #{post.end_time.to_s(:time_for_title)}" %></span>
      </h2>
      <div class="post-body">
        <p><%= post.kind_of_climbing.camelize %></p>
        <p><%= post.describe %></p>
      </div>
    </div>
  <% end %>

app/views/posts/new.html.erb
<%= turbo_frame_tag 'new_message' do %>
  <h2>New Post</h2>

  <%= render 'form', post: @post %>
  <%= link_to 'back', posts_path %>
<% end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="post">
  <h2>
    <span class="post-owner"><%= link_to @post.user.name, post_path(@post) %></span>
    <span class="date"><%= "#{@post.date.to_s(:date_for_title)}" %></span>
    <br>
    <span class="time"><%= "#{@post.start_time.to_s(:time_for_title)} - #{@post.end_time.to_s(:time_for_title)}" %></span>
  </h2>
  <div class="post-body">
    <p><%= @post.kind_of_climbing.camelize %></p>
    <p><%= @post.describe %></p>
  </div>

  <div class="post-link">
    <% if @post.user_id == current_user.id %>
      <%= link_to 'Edit', edit_post_path(@post) %> | 
    <% else %>
      <%= link_to 'Message', new_answer_path(post_id: @post.id, host_user_id: @post.user_id, answerer_user_id: current_user.id), class: 'button' %>
    <% end %>
    <%= link_to 'Back', posts_path %>
  </div>
</div>