config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'posts#index'
  resources :posts
  resources :users
  resources :answers
  resources :rooms

  patch '/answers/:id/unread', action: :unread, controller: 'answers'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header id="header-site">
  <div id="header-site-inner">
    <h1 class="title">
      <%= link_to 'Belayer', root_path %>
      <span class="tagline">This is an application which you can find your belay partner in your rock trip!</span>
    </h1>
    <nav>
      <li class="tab"><%= link_to 'Home', root_path, class: "button button-small button-inverse" %></li>
      <% if current_user %>
        <li class="tab"><%= link_to 'New Post', new_post_path, class: "button button-small button-inverse" %></li>
        <li class="tab"><%= link_to 'Message Box', rooms_path, class: "button button-small button-inverse" %></li>
        <li class="tab"><%= link_to 'Profile', user_path(current_user), class: "button button-small button-inverse" %></li>
        <li class="tab"><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "button button-small button-inverse" %></li>
      <% else %>
        <li class="tab"><%= link_to 'Log In', new_user_session_path, class: "button button-small button-inverse" %></li>
        <li class="tab"><%= link_to 'Sign Up', new_user_registration_path, class: "button button-small button-inverse" %></li>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Belayer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= turbo_include_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  </head>

  <body>
    <div id="container">
      <%= render 'layouts/header' %>
      <div id="contents">
        <%= yield %>
      </div>
    </div>
  </body>
</html>